# Things in {{CURLIES}} will be read from the process environment when the server starts up.
# The jrun launcher will typically load these from ~/.cloudos.env

serverName: histori-api

#publicUriBase: https://127.0.0.1
publicUriBase: {{PUBLIC_BASE_URI}}

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/histori
  user: histori
  password: {{HISTORI_DB_PASS}}

  hibernate:
    entityPackages: [ histori.model ]
    archivePackages: [ histori.archive ]
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hbm2ddlAuto: validate
    validationMode: ddl

staticAssets:
  baseUri: /
  assetRoot: site/
  localOverride: {{ASSETS_DIR}}
  mustacheCacheEnabled: false
  mustacheResourceRoot: site/
  utilPaths:
    INDEX_PATH: /index.html
    INDEX_ALIASES: /:/index.php
    LOCALIZE: /localize

http:
  port: {{HISTORI_SERVER_PORT}}
  baseUri: /api

jersey:
  resourcePackages: [ histori.resources, org.cobbzilla.wizard.server, org.cobbzilla.wizard.filters ]
  requestFilters: [ histori.auth.HistoriAuthFilter ]
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]

emailTemplateRoot: {{EMAIL_TEMPLATE_ROOT}}

emailSenderNames:
  welcome:
    fromName:  {{WELCOME_SENDER_NAME}}
    fromEmail: {{WELCOME_SENDER_EMAIL}}
  reset_password:
    fromName: {{RESET_PASSWORD_SENDER_NAME}}
    fromEmail: {{RESET_PASSWORD_SENDER_EMAIL}}

smtp:
  host: 127.0.0.1
  user: {{SYSTEM_MAILER_USERNAME}}
  password: {{SYSTEM_MAILER_PASSWORD}}
  tlsEnabled: true

sessionPassphrase: {{HISTORI_DATAKEY}}

assetStorage:
  type: s3
  config:
    accessKey: {{ASSETS_S3_ACCESS_KEY}}
    secretKey: {{ASSETS_S3_SECRET_KEY}}
    bucket: {{ASSETS_S3_BUCKET}}
    prefix: {{ASSETS_S3_PREFIX}}
    localCache: {{ASSETS_LOCAL_CACHE_DIR}}

threadPoolSizes:
  VoteSummaryDAO: 10
  NexusSummaryDAO: 10
