# Things in {{CURLIES}} will be read from the process environment when the server starts up.
# The jrun launcher will typically load these from ~/.cloudos.env

serverName: histori-api

#publicUriBase: https://127.0.0.1
publicUriBase: {{PUBLIC_BASE_URI}}

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/histori_master
  user: histori
  password: {{HISTORI_DB_PASS}}

  encryptionEnabled: true
  encryptionKey: '{{HISTORI_DB_ENCRYPTION_KEY}}'
  encryptorPoolSize: 5

  hibernate:
    entityPackages:
    - histori.model
    - org.cobbzilla.wizard.model.crypto   # for encrypted column support
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hbm2ddlAuto: validate
    validationMode: ddl

  shard:
    - name: histori-account
      entity: histori.model.Account
    - name: bookmark
      entity: histori.model.Bookmark
    - name: super-nexus
      entity: histori.model.SuperNexus
    - name: nexus
      entity: histori.model.Nexus
    - name: nexus-archive
      entity: histori.model.archive.NexusArchive
    - name: permalink
      entity: histori.model.Permalink
    - name: tag
      entity: histori.model.Tag
    - name: vote
      entity: histori.model.Vote
    - name: vote-archive
      entity: histori.model.archive.VoteArchive

staticAssets:
  baseUri: /
  assetRoot: site/
  localOverride: {{ASSETS_DIR}}
  mustacheCacheEnabled: false
  mustacheResourceRoot: site/
  utilPaths:
    INDEX_PATH: /index.html
    INDEX_ALIASES: /:/index.php
    LOCALIZE: /localize
  substitutions:
    /signup.html:
      recaptcha: {{RECAPTCHA_PUBLIC_KEY}}

http:
  port: {{HISTORI_SERVER_PORT}}
  baseUri: /api

jersey:
  resourcePackages: [ histori.resources, org.cobbzilla.wizard.server, org.cobbzilla.wizard.filters, org.cobbzilla.wizard.exceptionmappers ]
  requestFilters: [ histori.auth.HistoriAuthFilter ]
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]

emailTemplateRoot: {{EMAIL_TEMPLATE_ROOT}}

emailSenderNames:
  welcome:
    fromName:  {{WELCOME_SENDER_NAME}}
    fromEmail: {{WELCOME_SENDER_EMAIL}}
  reset_password:
    fromName: {{RESET_PASSWORD_SENDER_NAME}}
    fromEmail: {{RESET_PASSWORD_SENDER_EMAIL}}

smtp:
  host: {{HISTORI_SMTP_SERVER}}
  port: {{HISTORI_SMTP_PORT}}
  user: {{HISTORI_SMTP_USER}}
  password: {{HISTORI_SMTP_PASS}}
  tlsEnabled: true

redis:
  key: '{{HISTORI_REDIS_ENCRYPTION_KEY}}'
  prefix: histori

assetStorage:
  type: s3
  config:
    accessKey: {{ASSETS_S3_ACCESS_KEY}}
    secretKey: {{ASSETS_S3_SECRET_KEY}}
    bucket: {{ASSETS_S3_BUCKET}}
    prefix: {{ASSETS_S3_PREFIX}}
    localCache: {{ASSETS_LOCAL_CACHE_DIR}}

threadPoolSizes:
  VoteSummaryDAO: 10
  NexusSummaryDAO: 10

recaptcha:
  publicKey: {{RECAPTCHA_PUBLIC_KEY}}
  privateKey: {{RECAPTCHA_PRIVATE_KEY}}
