#!/bin/bash
#
# Usage: createalldb <count> <prefix>
#
# Create a master database and <count> database shards, using <prefix> as the name
#

function die {
  echo 1>&2 "${1}"
  exit 1
}

if [ ! -z "${PPSQL_COUNT}" ] ; then
  COUNT="${PPSQL_COUNT}"
else
  COUNT="${1:?no count given}" ; shift
fi
PREFIX="${1:?no prefix given}" ; shift

OPTS=""
if [ ! -z "${1}" ] ; then
  OPTS="${@}"
fi

i=0
while [ ${i} -lt ${COUNT} ] ; do
  echo "creating: ${PREFIX}_${i}"
  createdb ${OPTS} ${PREFIX}_${i}
  i=$((i + 1))
done

echo "creating: ${PREFIX}_master"
createdb ${OPTS} ${PREFIX}_master
