#!/bin/bash

BASE=$(cd $(dirname $0) && pwd)

for shard in histori-account preferred-owner blocked-owner bookmark super-nexus nexus nexus-archive permalink tag vote vote-archive map-image book feed ; do
  ${BASE}/../run.sh shard-gen-sql ${@} -S ${shard}
done
