#!/bin/bash

if [ ! -z "${PPSQL_COUNT}" ] ; then
  COUNT="${PPSQL_COUNT}"
else
  COUNT="${1:?no count given}" ; shift
fi
BASE=$(cd $(dirname $0) && pwd)

ARCHIVE=${1:?no SQL archive given}

dropdb histori_master
createdb histori_master
gzcat ${ARCHIVE} | psql -U histori histori_master
echo "delete from shard" | psql -U histori histori_master

i=0
while [ $i -lt ${COUNT} ] ; do
  dropdb histori_${i}
  createdb histori_${i}
  pg_dump histori_master | psql -U histori histori_${i}
  echo "drop table shard" | psql -U histori histori_${i}
done

${BASE}/init_standard_shards ${COUNT} | psql -U histori histori_master
